---
apiVersion: v1
kind: Service
metadata:
  name: acala-devnet
  labels:
    app: acala-devnet
spec:
  ports:
    - port: 9944
      name: node-ws
      protocol: TCP
    - port: 8547
      name: http
      protocol: TCP
    - port: 3331
      name: ws
      protocol: TCP
  clusterIP: None
  selector:
    app: acala-devnet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: acala-devnet
spec:
  selector:
    matchLabels:
      app: acala-devnet
  serviceName: acala-devnet
  replicas: 1
  template:
    metadata:
      labels:
        app: acala-devnet
    spec:
      containers:
        - name: acala
          image: acala-node
          args:
            - --dev
            - -lruntime=debug
            - -levm=debug
            - --mnemonic
            - "myth like bonus scare over problem client lizard pioneer submit female collect"
            - --ws-port=9944
            - --ws-external=true
            - --rpc-port=9933
            - --rpc-external=true
            - --rpc-cors=all
            - --rpc-methods=unsafe
          ports:
            - containerPort: 9944
              name: node-ws
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: node-ws
        - name: eth-rpc-adapter
          image: acala-eth-rpc-adapter
          command: ['yarn']
          args:
            - start
          env:
            - name: ENDPOINT_URL
              value: ws://localhost:9944
            #- name: SUBQL_URL
            #  value:
          ports:
            - containerPort: 8545
              name: http
              protocol: TCP
          ports:
            - containerPort: 3331
              name: ws
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: http
        - name: tests
          image: acala-deploy-node
          stdin: true
          command:
            - /bin/sh
            - -c
            - |
              sed -i 's/CHAIN_ID=0x2/CHAIN_ID=0x9/g' .env
              npm run migrate
              npx truffle exec scripts/register_solana_chain.js
              npx truffle exec scripts/register_terra_chain.js
              npx truffle exec scripts/register_eth_chain.js
              npx truffle exec scripts/register_bsc_chain.js
              nc -lkp 2000 0.0.0.0
          readinessProbe:
            periodSeconds: 1
            failureThreshold: 300
            tcpSocket:
              port: 2000
